=== AvalonServers/DescentPacks/schema/config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$ref": "#/definitions/16f01gsc2ppmp",
    "definitions": {
        "1muk6oewqpo1t": {
            "type": "object",
            "properties": {
                "folder": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "description": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "optional": {
                    "$ref": "#/definitions/95lpxckehe69"
                },
                "side": {
                    "enum": [
                        "CLIENT",
                        "SERVER",
                        "BOTH"
                    ],
                    "$ref": "#/definitions/x1cmzbou8shekf"
                },
                "websiteUrl": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "packageType": {
                    "enum": [
                        "FOLDER",
                        "CTOP",
                        "SINGLEFILE",
                        "CMOD2",
                        "MODPACK",
                        "MOD",
                        "ANY"
                    ],
                    "$ref": "#/definitions/xaygo1sgzyqyn"
                },
                "version": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "fileName": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "fileNameRegex": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "validMcVersions": {
                    "$ref": "#/definitions/x1atm94qhblv5r"
                },
                "invalidMcVersions": {
                    "$ref": "#/definitions/x1atm94qhblv5r"
                },
                "direct_useOriginalUrl": {
                    "$ref": "#/definitions/1u485b0ult91d"
                }
            },
            "additionalProperties": false
        },
        "x2w2015zeqzgf": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/6cdta9iwtw5d"
            }
        },
        "x1o90evh20qk1r": {
            "type": "string",
            "enum": [
                "Release",
                "Beta",
                "Alpha"
            ]
        },
        "x1cmzbou8shekf": {
            "if": {
                "type": "string"
            },
            "else": {
                "type": "null"
            },
            "enum": [
                "CLIENT",
                "SERVER",
                "BOTH"
            ]
        },
        "x3wcko3mv5xj3": {
            "type": "string",
            "enum": [
                "MODS",
                "RESOURCE_PACKS"
            ]
        },
        "u8vbjk4a30n5": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/x186d2oiqx3gn3"
            }
        },
        "xm0v4gp91e3un": {
            "type": "object",
            "properties": {
                "include": {
                    "$ref": "#/definitions/x2w2015zeqzgf"
                },
                "exclude": {
                    "$ref": "#/definitions/x2w2015zeqzgf"
                }
            },
            "additionalProperties": false
        },
        "4holsd0m641t": {
            "if": {
                "type": "string"
            },
            "else": {
                "type": "null"
            },
            "enum": [
                "starred",
                "avoid"
            ]
        },
        "xenpjj19afmyn": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/1f2g39y1n6cjl"
            }
        },
        "6cdta9iwtw5d": {
            "type": "string"
        },
        "x186d2oiqx3gn3": {
            "type": "object",
            "properties": {
                "mcVersions": {
                    "$ref": "#/definitions/x2w2015zeqzgf"
                }
            },
            "additionalProperties": false
        },
        "16f01gsc2ppmp": {
            "type": "object",
            "properties": {
                "$schema": {
                    "$ref": "#/definitions/6cdta9w4b4yo"
                },
                "curseforgeGenerators": {
                    "$ref": "#/definitions/xwlxe69mmqp6n"
                },
                "forgeGenerators": {
                    "$ref": "#/definitions/u8vbjk4a30n5"
                },
                "fabricGenerators": {
                    "$ref": "#/definitions/xjrj819p1q1of"
                },
                "overrides": {
                    "$ref": "#/definitions/xenpjj19afmyn"
                }
            },
            "additionalProperties": false,
            "required": [
                "$schema",
                "curseforgeGenerators",
                "forgeGenerators",
                "fabricGenerators",
                "overrides"
            ]
        },
        "4gp058leuw3l": {
            "if": {
                "type": "array"
            },
            "else": {
                "type": "null"
            },
            "items": {
                "enum": [
                    "Release",
                    "Beta",
                    "Alpha"
                ],
                "$ref": "#/definitions/x1o90evh20qk1r"
            }
        },
        "95lpxckehe69": {
            "if": {
                "type": "object"
            },
            "else": {
                "type": "null"
            },
            "properties": {
                "selected": {
                    "$ref": "#/definitions/1u485b0ult91d"
                },
                "recommendation": {
                    "enum": [
                        "starred",
                        "avoid"
                    ],
                    "$ref": "#/definitions/4holsd0m641t"
                },
                "files": {
                    "$ref": "#/definitions/xm0v4gp91e3un"
                }
            },
            "additionalProperties": false
        },
        "x1atm94qhblv5r": {
            "if": {
                "type": "array"
            },
            "else": {
                "type": "null"
            },
            "items": {
                "$ref": "#/definitions/6cdta9iwtw5d"
            }
        },
        "x1qxf8lr0t3ytb": {
            "type": "object",
            "properties": {
                "folder": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "description": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "optional": {
                    "$ref": "#/definitions/95lpxckehe69"
                },
                "side": {
                    "enum": [
                        "CLIENT",
                        "SERVER",
                        "BOTH"
                    ],
                    "$ref": "#/definitions/x1cmzbou8shekf"
                },
                "websiteUrl": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "packageType": {
                    "enum": [
                        "FOLDER",
                        "CTOP",
                        "SINGLEFILE",
                        "CMOD2",
                        "MODPACK",
                        "MOD",
                        "ANY"
                    ],
                    "$ref": "#/definitions/xaygo1sgzyqyn"
                },
                "version": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "fileName": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "fileNameRegex": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "validMcVersions": {
                    "$ref": "#/definitions/x1atm94qhblv5r"
                },
                "invalidMcVersions": {
                    "$ref": "#/definitions/x1atm94qhblv5r"
                },
                "curse_releaseTypes": {
                    "$ref": "#/definitions/4gp058leuw3l"
                },
                "curse_useOriginalUrl": {
                    "$ref": "#/definitions/1u485b0ult91d"
                },
                "curse_skipFingerprintCheck": {
                    "$ref": "#/definitions/1u485b0ult91d"
                }
            },
            "additionalProperties": false
        },
        "xaygo1sgzyqyn": {
            "if": {
                "type": "string"
            },
            "else": {
                "type": "null"
            },
            "enum": [
                "FOLDER",
                "CTOP",
                "SINGLEFILE",
                "CMOD2",
                "MODPACK",
                "MOD",
                "ANY"
            ]
        },
        "xffp8li28wqv3": {
            "type": "object",
            "properties": {
                "folder": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "description": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "optional": {
                    "$ref": "#/definitions/95lpxckehe69"
                },
                "side": {
                    "enum": [
                        "CLIENT",
                        "SERVER",
                        "BOTH"
                    ],
                    "$ref": "#/definitions/x1cmzbou8shekf"
                },
                "websiteUrl": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "packageType": {
                    "enum": [
                        "FOLDER",
                        "CTOP",
                        "SINGLEFILE",
                        "CMOD2",
                        "MODPACK",
                        "MOD",
                        "ANY"
                    ],
                    "$ref": "#/definitions/xaygo1sgzyqyn"
                },
                "version": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "fileName": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "fileNameRegex": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "validMcVersions": {
                    "$ref": "#/definitions/x1atm94qhblv5r"
                },
                "invalidMcVersions": {
                    "$ref": "#/definitions/x1atm94qhblv5r"
                },
                "jenkins_jenkinsUrl": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                }
            },
            "additionalProperties": false
        },
        "1f2g39y1n6cjl": {
            "properties": {
                "type": {
                    "type": "string",
                    "enum": [
                        "common",
                        "curse",
                        "direct",
                        "jenkins",
                        "local"
                    ]
                }
            },
            "anyOf": [
                {
                    "$ref": "#/definitions/2hulzmb4d2wx"
                },
                {
                    "$ref": "#/definitions/x1qxf8lr0t3ytb"
                },
                {
                    "$ref": "#/definitions/1muk6oewqpo1t"
                },
                {
                    "$ref": "#/definitions/xffp8li28wqv3"
                },
                {
                    "$ref": "#/definitions/u98b9e39fv29"
                }
            ],
            "required": [
                "type"
            ]
        },
        "u98b9e39fv29": {
            "type": "object",
            "properties": {
                "folder": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "description": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "optional": {
                    "$ref": "#/definitions/95lpxckehe69"
                },
                "side": {
                    "enum": [
                        "CLIENT",
                        "SERVER",
                        "BOTH"
                    ],
                    "$ref": "#/definitions/x1cmzbou8shekf"
                },
                "websiteUrl": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "packageType": {
                    "enum": [
                        "FOLDER",
                        "CTOP",
                        "SINGLEFILE",
                        "CMOD2",
                        "MODPACK",
                        "MOD",
                        "ANY"
                    ],
                    "$ref": "#/definitions/xaygo1sgzyqyn"
                },
                "version": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "fileName": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "fileNameRegex": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "validMcVersions": {
                    "$ref": "#/definitions/x1atm94qhblv5r"
                },
                "invalidMcVersions": {
                    "$ref": "#/definitions/x1atm94qhblv5r"
                },
                "local_fileSrc": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                }
            },
            "additionalProperties": false
        },
        "2hulzmb4d2wx": {
            "type": "object",
            "properties": {
                "folder": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "description": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "optional": {
                    "$ref": "#/definitions/95lpxckehe69"
                },
                "side": {
                    "enum": [
                        "CLIENT",
                        "SERVER",
                        "BOTH"
                    ],
                    "$ref": "#/definitions/x1cmzbou8shekf"
                },
                "websiteUrl": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "packageType": {
                    "enum": [
                        "FOLDER",
                        "CTOP",
                        "SINGLEFILE",
                        "CMOD2",
                        "MODPACK",
                        "MOD",
                        "ANY"
                    ],
                    "$ref": "#/definitions/xaygo1sgzyqyn"
                },
                "version": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "fileName": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "fileNameRegex": {
                    "$ref": "#/definitions/1kii6t544y7sx"
                },
                "validMcVersions": {
                    "$ref": "#/definitions/x1atm94qhblv5r"
                },
                "invalidMcVersions": {
                    "$ref": "#/definitions/x1atm94qhblv5r"
                }
            },
            "additionalProperties": false
        },
        "1xy3kesy5ce81": {
            "type": "boolean"
        },
        "xwlxe69mmqp6n": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/x488mpoavabl"
            }
        },
        "1u485b0ult91d": {
            "if": {
                "type": "boolean"
            },
            "else": {
                "type": "null"
            }
        },
        "x488mpoavabl": {
            "type": "object",
            "properties": {
                "section": {
                    "enum": [
                        "MODS",
                        "RESOURCE_PACKS"
                    ],
                    "$ref": "#/definitions/x3wcko3mv5xj3"
                },
                "categories": {
                    "$ref": "#/definitions/x2w2015zeqzgf"
                },
                "mcVersions": {
                    "$ref": "#/definitions/x2w2015zeqzgf"
                }
            },
            "additionalProperties": false,
            "required": [
                "section"
            ]
        },
        "19ymerplvvxtt": {
            "type": "object",
            "properties": {
                "requireStable": {
                    "$ref": "#/definitions/1xy3kesy5ce81"
                },
                "mcVersions": {
                    "$ref": "#/definitions/x2w2015zeqzgf"
                }
            },
            "additionalProperties": false
        },
        "1kii6t544y7sx": {
            "if": {
                "type": "string"
            },
            "else": {
                "type": "null"
            }
        },
        "6cdta9w4b4yo": {
            "type": "string"
        },
        "xjrj819p1q1of": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/19ymerplvvxtt"
            }
        }
    }
}

=== AvalonServers/DescentPacks/config.json
{
    "$schema": "./schema/config.schema.json",
    "curseforgeGenerators": {
		"Forge": {
			"section": "MODS",
			"mcVersions": [
				"1.12", "1.12.1", "1.12.2"
			]
		}
    },
    "forgeGenerators": {
        "Forge_12_2": {
          "mcVersions": [
            "1.12.2"
          ]
        }
    },
    "fabricGenerators": {
    },
    "overrides": {
    }
}
